name: Delete Old Tags

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  delete_old_tags:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Delete old tags
      run: |
        # Set the date 30 days ago
        OLDEST_DATE=$(date -d "30 days ago" +%Y-%m-%d)
        
        # List all tags
        TAGS=$(git tag -l)

        # Loop through tags and delete those older than 60 days
        for TAG in $TAGS; do
          TAG_DATE=$(git log -1 --format=%ai $TAG)
          if [[ "$TAG_DATE" < "$OLDEST_DATE" ]]; then
            git tag -d $TAG
            git push origin :refs/tags/$TAG
            echo "Deleted tag: $TAG"
          fi
        done
      env:
        GITHUB_TOKEN: "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"
